stages:
  - build
  - deploy

default:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/network:latest .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/network:latest 

deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/network:latest
  script:
    - docker run $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/network:latest curl google.com
    - docker run $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/network:latest ping -c 4 google.com
    - docker run $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/network:latest traceroute google.com
    - docker run $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/network:latest dig google.com